EXCEPTION HANDLING

What is the difference between error and exception handling?
example of syntax error:
if x ==10 (missing ':')
    for x in range(10):
        print(x)
output:
1. SyntaxError: expected ':'

 - syntax error is known as compile time error.
Compile Time / Interpretation Time:
    - converting .py file into byte code. (or) byte code transformation.
    .py --> byte code --> binary file

When program run line by line, If missing any line mistake don't execute next line.

2. Exception:
    - Exception is runtime error,
    - After your python code getting is convert into binary code.
    - some error can happen during runtime, those error is known as exception.

    ex:
    x=int(input("enter your no1: "))
    y=int(input("enter your no2: "))
    print(x/y) # infinity

    # put y value is 0 --> ZeroDivisionError: division by zero
    # put y value is any str --> ValueError: invalid literal for int() with base 10: 'x'

    output:
    ZeroDivisionError: division by zero - (this is called Exception)
    ValueError: invalid literal for int() with base 10: 'x'

    - An unexpected event occurred that stop the normal flow of a program is known as exception.

    print(arunkumar) # missing single or double quotes

    output:
    - NameError: name 'arunkumar' is not defined

    print("Arun"+5) # two str are concatenate

    output:
    - TypeError: can only concatenate str (not "int") to str

    file = open("abc.txt")
    print(file.read())

    output:
    - FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'

- TypeError, NameError, ZeroDivisionError, ValueError and FileNotFoundError are python class.

Object:
    - It has real time entity.
    - It is combinations of states and behaviour.
    ex: Indian Human
    States - Colour, Height, Hair Style and Dressing, etc.,
    Behaviour - VoterId(), Vote(), AadharCard()

Class:
    - class is a template or blueprint. where we are keeping all the functions and data member inside.
    - classes are reusable
    - class contains combinations of variables and  methods.

Class is a collection of objects, Not why?
- add object in list, list is not a class. but list contain collection of objects.

Exception Handling:
   Syntax:
            try:
                //Block of code
            except ExceptionErrorName:
                //Block of code

                        or
            try:
                //Block of code
            except ExceptionErrorName, ExceptionErrorName : # for more exception
                //Block of code
            ex:
                try:
                    print(10/0)
                except ZeroDivisionError as msg:
                    print(type(msg))

                try:
                    print(10/0)
                except ZeroDivisionError:
                    print(100/5)

   - Error raised in try block. so alternative solution given by except block.

            try:
                # Exception possible area
            except:
                # Exception Handling area

Incase Exeception Name is don't know. you can put except only atlast.

Python Exception Handling Keywords:
            - try
            - except
            - else
            - finally
            - raise

How to read online file reads?
    - First read browser
    - try python web drivers

split():
    - with the delimiter given its splits the words or sentance.
    delimiter - , : . / - @

    ex:
        file =open(r'/home/arun/Music/python/ExceptionHandling/pincodes.txt')
        for each_line in file:
            (city,pincode) = each_line.split("-")
            print("pincode of",city,end="")
            print("is",pincode,end="")
        file.close()
--------------------------------------------------------------------------------------------------------------------------------
FileNotFoundException Handling

        try:
            file =open(r'/home/arun/Music/python/ExceptionHandling/pincode.txt')
        except:
            print("check the file location")

        Output:
        check the file location

Note: If I create a try block, it compulsory present except or finally block.

        eg: Incase missing of except or finally block, the machine throws syntax error

            SyntaxError: expected 'except' or 'finally' block

    -Nested try and except block is possible.
    -One try more than one except block is possible.


pass - Keyword --> Immediate skip into exception, it is not a solution, used for temporary only. after find the exception to fix the except block.

Default Exception at present end of all exceptions like:

    ex:
        try:
            // Block of code
        except ExceptionName:
            // Block of code
        except:     -----------------> Default exception
            // Block of code

Finally:
    - Finally always run all time
    Usage of finally:
        -DB cleaning, connection closing 
    ex: automatically logout, session expired scenarios.

    finally:
        # DB closing code
        # connection closing code

# MicroProgram 
import sys

inputList = ['a', 0, False, 1, 2, 8, 10]

for entry in inputList:
    try:
        print("The entry is", entry)
        r = 1/entry
        break
    except:
        print("Opps!", sys.exc_info()[0], "occurred.") # change the index number 0, 1 and 2. output will change.
        print("Next entry")
        print()
print("The reciprocal of",entry, "is",r)

sys.exc_info() - system.exception_information()

Q&A:
1. Exception:
    - Exception during runtime unexpected event that stop the normal flow of a program. In python, Exception is a class.

2. Error vs Exception:
    - SyntaxError can be found during compile time error. But exception can be handled by the programmer using try and except block.

3. Few Built-in Exception:
    - ValueError
    - ZeroDivisionError
    - TypeError
    - FileNotFoundError
    - NameError
    - AttributeError

4. Exception Keywords in Python:
    - try
    - except
    - finally
    - raise
    - else

5. try without except:
    - try without except is an error. try block must have except block or finally block or both.

6. try with multiple except:
    - It's possible. we can multiple except block for each Exception class in python.

7. How do you handle exceptions if you don't know the exact exception class name in python?
    - yes, it's possible, if we have don't know the what exceptions will raise in try block at that time we can go for Default except block.

8. try except finally:
    - here order is important, only after except, finally should be present. Finally block will be executed. if an exception raised or not.

9. Default except:
    - if we don't provide handling code by default exception are handled by PVM(Python Virtual Machine).

10. can we handle more than one exception in a single except statement?
    - Yes. we can handle the exception separate by using the comma (,).

    ex: except(AttributeError, ValueError):
            pass







